name: Whatsapp-Signal-Notifier Build Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build executables
      run: sh ./build_script.sh
    
    - uses: actions/upload-artifact@v2
      with:
        name: whatsapp-signal-notifier-windows
        path: whatsapp-signal-notifier-windows.zip
        
    - uses: actions/upload-artifact@v2
      with:
        name: whatsapp-signal-notifier-mac
        path: whatsapp-signal-notifier-mac.zip
        
    - uses: actions/upload-artifact@v2
      with:
        name: whatsapp-signal-notifier-linux
        path: whatsapp-signal-notifier-linux.zip
